### ISSUE TITLE
Wrong validation error 

### ISSUE THREAD

**Issue by denspiro** [ghaschel/vscode-angular-html#1]
![image](https://user-images.githubusercontent.com/944858/47914107-0c2d4c00-dea7-11e8-87d1-f24dbc888fbb.png)
This is perfectly valid but marked as an error.

**Comment by ghaschel** [comment]
Did you try disabling all of your plugins? I'm not able to reproduce this. I even disabled all of my plugins. I tested with angular-language-services enabled and disabled.

This plugin doesn't make any validity checks, it only applies highlighting. Theoretically it is not supposed set anything as invalid, except for applying invalid color for invalid attributes such as `align` on `div` tags, and invalid tags such as `acronym`.

![image](https://user-images.githubusercontent.com/5878866/47972435-55d28e00-e083-11e8-9433-f3ce8e8cf3ba.png)

**Comment by denspiro** [comment]
You right. It was a different plugin.
