### ISSUE TITLE
Support new `@let` template syntax

### ISSUE THREAD

**Issue by joelkesler** [ghaschel/vscode-angular-html#101]
Using `@let` in a template causes syntax coloring bugs

Example:
<img width="591" alt="image" src="https://github.com/user-attachments/assets/84ffbc4b-039c-43c7-b8dd-59aa27bc18ab">

More info about `@let`:
https://blog.angular.dev/introducing-let-in-angular-686f9f383f0f

**Comment by ghaschel** [comment]
Thanks for reporting it. I implemented it and I just published a new version containing this feature.

Please, let me know if you find anything wrong 😅

**Comment by joelkesler** [comment]
Oh wow, that was quick! Thanks!

Edit: so far so good

<img width="590" alt="image" src="https://github.com/user-attachments/assets/824e4ce9-e589-4d78-b26d-5890ee28ee27">
