### ISSUE TITLE
color of minimized boolean html attributes (required, disabled etc.)

### ISSUE THREAD

**Issue by vLutsevich** [ghaschel/vscode-angular-html#11]
In html language exists boolean attributes that we can type in minimized syntax without values, I mean required, disabled, hidden (and may be other, I don't other remember by heart). And I think it should be turquoise color also, don't white color as now.
![image](https://user-images.githubusercontent.com/8142982/48699329-41050700-ebfa-11e8-8d0d-405e6a993f5b.png)

**Comment by ghaschel** [comment]
This is an old bug I'm actually aware already. But thanks anyway for pointing it out =]

**Comment by ghaschel** [comment]
[0.0.31](https://github.com/ghaschel/vscode-angular-html/commit/63f3763f5d15ad1a584317653e8bbef8e2e8c137) fixes this
