### ISSUE TITLE
color of DOM property name

### ISSUE THREAD

**Issue by vLutsevich** [ghaschel/vscode-angular-html#12]
Maybe it makes sense to use another color than turquoise (that is a color of html attributes) inside of binding braces, that will visually show when you do binding you mean DOM property, that's different from html attribute. But it need to consider that attribute binding it should be turquoise, 
<tr><td [attr.colspan]="1 + 1">One-Two</td></tr>

**Comment by ghaschel** [comment]
Good suggestion, I'll do this

**Comment by ghaschel** [comment]
Do you mean something like this?

![sem titulo](https://user-images.githubusercontent.com/5878866/48706137-7a317d00-ebe2-11e8-9bd9-f3f22d049b18.png)

**Comment by vLutsevich** [comment]
yes, I mean that, it's cool :)
but I have doubts maybe it's no such good idea, maybe it's too many colors - and it's creating a visual noise.
or maybe it needs to do an option to choose who wants like that or not.

**Comment by ghaschel** [comment]
The idea of adding an option is nice.
But it will require an option to rebuild the syntax file with the proper settings, so it may be an a feature for the future...

For now I need to focus in making errorless and easy to read. I can see it as a good contextual way of separating attributes from binding, but I'm not sure if needed for now. 

I'll create a poll for that

**Comment by ghaschel** [comment]
Do you think angular directives (bindings, ngIf, nfFor) should be differentiated from HTMl attributes in color?
![with differentiation](https://user-images.githubusercontent.com/5878866/48707849-dfd43800-ebe7-11e8-8a3f-931e4b3d3bfc.png)
![without differentiation](https://user-images.githubusercontent.com/5878866/48707855-e2cf2880-ebe7-11e8-8233-1182d3d4b013.png)

/polls 'Yes' 'No'

**Comment by ghaschel** [comment]
Do you think angular directives (bindings, ngIf, nfFor) should be differentiated from HTMl attributes in color?
![with differentiation](https://user-images.githubusercontent.com/5878866/48707849-dfd43800-ebe7-11e8-8a3f-931e4b3d3bfc.png)
![without differentiation](https://user-images.githubusercontent.com/5878866/48707855-e2cf2880-ebe7-11e8-8233-1182d3d4b013.png)

/polls 'Yes' 'No'

**Comment by ghaschel** [comment]
Do you think angular directives (ngFor, ngIf, bindings) should be differentiated in color from html attributes?
## With differentiation
![with differentiation](https://user-images.githubusercontent.com/5878866/48708280-502f8900-ebe9-11e8-8f72-f5ce25c84a24.png)

## Without differentiation
![without differentiation](https://user-images.githubusercontent.com/5878866/48708950-26776180-ebeb-11e8-9e8f-12d4bb0fb56a.png)


# Vote here:

[![](https://api.gh-polls.com/poll/01CWP0EBPWCDYEJYEKJS59WXHV/Yes)](https://api.gh-polls.com/poll/01CWP0EBPWCDYEJYEKJS59WXHV/Yes/vote)

[![](https://api.gh-polls.com/poll/01CWP0EBPWCDYEJYEKJS59WXHV/No)](https://api.gh-polls.com/poll/01CWP0EBPWCDYEJYEKJS59WXHV/No/vote)

**Comment by vLutsevich** [comment]
perhaps there is an error with screens, because for me they are both has differentiation from html attributes. html attributes had a turquoise color before.

**Comment by ghaschel** [comment]
Sorry, I uploaded the wrong image, changed now

**Comment by ghaschel** [comment]
[0.0.31](https://github.com/ghaschel/vscode-angular-html/commit/63f3763f5d15ad1a584317653e8bbef8e2e8c137) fixed this
