### ISSUE TITLE
let word color inside *ngFor

### ISSUE THREAD

**Issue by vLutsevich** [ghaschel/vscode-angular-html#13]
Now word 'let' has a white color, but I think it must be dark blue as 'of' word  or words 'let' and 'const' in .ts files.
![image](https://user-images.githubusercontent.com/8142982/48705784-3868fc80-ec0b-11e8-9aee-4c2093bd9c6a.png)

**Comment by ghaschel** [comment]
Which theme are you using?

It was supposed to show in purple, not in dark blue if you're using dark-plus-syntax or VSCode Dark+

**Comment by vLutsevich** [comment]
Oh, I understood. For 'dark-plus-syntax' it's really purple colored and it color fits me because I am usually using this theme. But on the screen was 'Dark+ (Default dark)'. I was switched to it ocсasionaly.

**Comment by ghaschel** [comment]
Thanks for pointing out. I will change scopes to match `of` and keep it purple under dark-plus-syntax

**Comment by ghaschel** [comment]
[0.0.31](https://github.com/ghaschel/vscode-angular-html/commit/63f3763f5d15ad1a584317653e8bbef8e2e8c137) fixed this
