### ISSUE TITLE
Inline template support

### ISSUE THREAD

**Issue by rexebin** [ghaschel/vscode-angular-html#14]
Thanks for the great extension. Is there any plan for supporting inline template?

**Comment by ghaschel** [comment]
Thanks for your feedback. Do you mean making the same as [angular-inline](https://marketplace.visualstudio.com/items?itemName=natewallace.angular2-inline)?

**Comment by rexebin** [comment]
Yes, supporting the inline template, same as angular2-inline, eventually
replacing it hopefully. I think vscode-angular-html offers better
highlighting and there is a lot of room to it.

**Comment by ghaschel** [comment]
I'm happy to hear that, thank you.

I'll take a look at it this week and let you know if its viable to create a fork of angular2-inline

**Comment by rexebin** [comment]
The way vscode-angular-html works could not support inline template?

**Comment by ghaschel** [comment]
It could work, and it shouldn't be hard to apply it. I just have to look into the syntax file from angular2-inline to be sure

**Comment by rexebin** [comment]
@ghaschel I made a Dracula theme, now updated to work with your extension. 
There are a few area needs fixing: 
1. template variable starting with # is treated the same as angular properties `support.type.object.module.html`. Should be treated separately.
2. `{{}}` interpolation in html properties are not treated, still seen as regular strings.
3. angular component class variable and method are partially supported, meaning `variable.other.property.js` and `variable.other.readwrite.js` are somewhat not 100% correctly recognized.
4. angular ng-template syntax sugar starting with * could have its own style.

Once again, your extension is amazing. thanks for the hard work.

**Comment by ghaschel** [comment]
Not sure I understood what you meant with 1.
I will look into 2 and 3.

About 4, do you mean something like [this](https://github.com/ghaschel/vscode-angular-html/issues/12#issuecomment-439883428)?

**Comment by rexebin** [comment]
For no. 1, what I mean is the #dialogMode template variable as shown below, is recognized as `support.type.object.module.html`  same as angular component inputs. It is not possible to give it a different style.

```
<ng-template #dialogMode>
  
</ng-template>
```

As for No.4, is that I want to make the stuff starting with * like below `*ngTemplateOutlet` a different style (italic) as webstorm does, but it is now the same signature as above `support.type.object.module.html`. 

`<ng-container *ngTemplateOutlet="titleTemplate ? titleTemplate : defaultTitleTemplate"></ng-container></ng-container>`

Thanks.

**Comment by rexebin** [comment]
Allow me to further explain No. 3. From what I understand, the extension recognises component properties as `variable.other.property.js` and methods as `variable.other.readwrite.js`. However, quite often, properties are recognized as `variable.other.readwrite.js`. I have yet to see a method recognized as a property.

**Comment by ghaschel** [comment]
Ohhh, I see. I. It actually uses a unified regex to recognize all of angular patterns. But I guess it won't be too much of a hassle to separate that.

Will applying the same parent scope but differentiating the child ones enough?

eg:
support.type.object.module.templatevariable and support.type.object.module.templateoutlet

**Comment by rexebin** [comment]
> Ohhh, I see. I. It actually uses a unified regex to recognize all of angular patterns. But I guess it won't be too much of a hassle to separate that.
> 
> Will applying the same parent scope but differentiating the child ones enough?
> 
> eg:
> support.type.object.module.templatevariable and support.type.object.module.templateoutlet

*ngTemplateOutlet is one of them, angular has many of these kind, *ngIf, *ngFor etc.. since they all start with *, I think treat all of them as the same type may be easier.

**Comment by ghaschel** [comment]
> Allow me to further explain No. 3. From what I understand, the extension recognises component properties as `variable.other.property.js` and methods as `variable.other.readwrite.js`. However, quite often, properties are recognized as `variable.other.readwrite.js`. I have yet to see a method recognized as a property.

I see, I think its the same as #7, the extension actually uses a built in pattern for js expressions. I think it would have to be rewritten.

**Comment by ghaschel** [comment]
> > Ohhh, I see. I. It actually uses a unified regex to recognize all of angular patterns. But I guess it won't be too much of a hassle to separate that.
> > Will applying the same parent scope but differentiating the child ones enough?
> > eg:
> > support.type.object.module.templatevariable and support.type.object.module.templateoutlet
> 
> *ngTemplateOutlet is one of them, angular has many of these kind, *ngIf, *ngFor etc.. since they all start with *, I think treat all of them as the same type may be easier.

Noted that, It would allow way more customizations via themes.

**Comment by ghaschel** [comment]
I'm not really sure how wrong it is, but how does it sound in theme development to use a scope that doesn't necessarily has something to do with what is being matched?

eg: <div `class`="test" (`click`)="test()"></div>

The correct scope for `class` would be `entity.other.attribute-name`, but that would apply a color that has been used already a large number of times, and not allowing a good highlighting. For that matter, i apply the `support` scope, and `constant.numeric` for `click`. 

I prioritized visual differentiation over proper scope matching.

**Comment by rexebin** [comment]
> I'm not really sure how wrong it is, but how does it sound to use a scope that doesn't necessarily has something to do with what is being matched?
> 
> eg: <div `class`="test" (`click`)="test()">
> 
> The correct scope for `class` would be `entity.other.attribute-name`, but that would apply a color that has been used already a large number of times, and not allowing a good highlighting. For that matter, i apply the `support` scope, and `constant.numeric` for `click`.
> 
> I prioritized visual differentiation over proper scope matching.

I am not sure I understand. But for <div class="test" (click)="test()">, the test in class would be simply a css class, same as other regular html markups. in `(click)="test()"`, `test()` would be component method, according to current scope, it is `variable.other.readwrite.js`.

There could be a simply and performant solution, could you apply a regex to separate component properties and methods by judging if they tail a empty `()` with parameters. The solution would miss the getters, but it would serve the purpose for now.

**Comment by rexebin** [comment]
> I'm not really sure how wrong it is, but how does it sound in theme development to use a scope that doesn't necessarily has something to do with what is being matched?
> 
> eg: <div `class`="test" (`click`)="test()">
> 
> The correct scope for `class` would be `entity.other.attribute-name`, but that would apply a color that has been used already a large number of times, and not allowing a good highlighting. For that matter, i apply the `support` scope, and `constant.numeric` for `click`.
> 
> I prioritized visual differentiation over proper scope matching.

If the class="test" is: class="{{test}}", the {{test}} is a interpolation of a component property `test`, currently not recognized, which is my point No.2 above.

**Comment by ghaschel** [comment]
I understand all of that, I i actually meant about the scopes themseves, not for what is being matched...

The correct scope for `class` or `title` would be `entity.other.attribute-name`, but I'm using `support.something.other-something` for a more diverse highlighting. How weird or wrong would that be for someone theming, as I'm planning to use a more customized scope naming now that you mentioned the angular sugar issue.

Would it be considered wrong in theming to have an attribute-name with the support scope applied, for example?

**Comment by rexebin** [comment]
For theming, all we are using are the TM Scope that we can get from the
inspector in vscode. The more the scopes differentiated, the more styles
could be applied, the better.

**Comment by rexebin** [comment]
When you add scopes, could you please add a scope for method parameters as well. Thank you!

**Comment by ghaschel** [comment]
no2 was fixed in [0.0.31](https://github.com/ghaschel/vscode-angular-html/commit/63f3763f5d15ad1a584317653e8bbef8e2e8c137)

1, 2, 4, and scopes for method parameters in a near future.

**Comment by rexebin** [comment]
@ghaschel I installed 0.0.31. Now angular component inputs `[propertyName]`, angular component outputs/events `(click)`,  template variables `#variableName` and ng-template syntax like `*ngIf`  are recognized as `constant.numeric.decimal.js`, which is not correct in my opinion. I thought you may want to know

**Comment by ghaschel** [comment]
That is what i was asking about using a scope that doesn't necessarely represent what is matched... I, personally, would like to kee the highlithing very clear, separating angular directives from HTML attributes... I also don't think that `constant.numerical.decimal.js` is the best choice, and the best i could do to mantain this color scheme is use `constant.numeric.angular.directive` instead. I would have to keep `constant.numeric.` as a prefix, otherwise it will not inherit any color. 

I did a master rewrite in the plugin today, it is now way more performant and optimized. It's in my plans to rethink all of the scope names. But I'll only do this when separating the angular directives, after dealing with the JS pattern matching.

**Comment by rexebin** [comment]
In this case, I will adjust my theme instead.

**Comment by ghaschel** [comment]
As soon as i update the scope names I'll write a .MD file poiting out all names in case someone want to support this extension. I'll let you know then.

**Comment by rexebin** [comment]
@ghaschel I updated the theme [Dracula Theme - WebStorm Edition](https://marketplace.visualstudio.com/items?itemName=rexebin.dracula). I can confirm that using `constant.numerical.decimal.js` is just fine because it has many parent signatures helping to select and differentiate from numerical values. However, using `constant.numeric.angular.directive` would be better.

**Comment by shayded-exe** [comment]
Any update on this? Would be really nice to have.

**Comment by ghaschel** [comment]
Firstly, sorry for taking so long to answer and give this a shot.

I managed to start to make it work. But it is still a long run, the scopes are not correctly applied yet and it now only works if Angular Language Service is disabled.

I will create another repository for this project, so then you can follow the progress there.
![image](https://user-images.githubusercontent.com/5878866/71723587-f3525a80-2e0b-11ea-8d5a-becbb6199da3.png)

**Comment by ghaschel** [comment]
You can follow the progress in this repository: https://github.com/ghaschel/vscode-angular-ts

I will make this plugin in my free time. I am closing this issue now. Thank you for the patience

**Comment by azephiris** [comment]
Still nothing?

**Comment by ghaschel** [comment]
Is this still awaited? I thought the angular team was providing inline template support already with the angular-language-service plugin...

If you guys still expect this, I can definitely work on it

**Comment by zeljkoantich** [comment]
> I thought the angular team was providing inline template support already with the angular-language-service plugin...

They are.

The thing is that Angular Language Service inline template highlight has some conflicts with `vscode-angular-html` and it's fully operational only if `vscode-angular-html` is disabled.

**Comment by ghaschel** [comment]
Better late than never I guess. But here it is: [Inline Template Support](https://marketplace.visualstudio.com/items?itemName=ghaschel.vscode-angular-inline)

**Comment by urielzen** [comment]
Holy wacamole, thank you
