### ISSUE TITLE
Putting '.%' inside in attribute name breaks syntax highlighting

### ISSUE THREAD

**Issue by matulkum** [ghaschel/vscode-angular-html#17]
For example like this: `[style.stroke-width.%]="100"`

The Angular Material lib for example make use of this style. Check out this file: https://github.com/angular/material2/blob/master/src/lib/progress-spinner/progress-spinner.html

Cheers

**Comment by ghaschel** [comment]
It doesn't seem to reproduce here. Running VSCode on MacOS.
Did you try disabling other extensions?

![screen shot 2018-12-10 at 00 36 51](https://user-images.githubusercontent.com/5878866/49707828-38f62100-fc14-11e8-87c6-d7e467f8c1f4.png)

**Comment by ghaschel** [comment]
I just arrived at work and tested on windows. Also didn't reproduce

**Comment by matulkum** [comment]
You are right. There must have been a mistake in my code somewhere else. I actually cannot reproduce myself ;)

Sorry for spamming. Let's close this issue.
