### ISSUE TITLE
HTML support with 1.0

### ISSUE THREAD

**Issue by vaindil** [ghaschel/vscode-angular-html#18]
I saw in the changelog that you changed the language ID. Is there a way to inherit from the base HTML type though? Not sure how VS Code works with this. Since the change I've lost basically all HTML support in components. You can see the difference in the gifs below.

![disabled](https://user-images.githubusercontent.com/771134/49828961-381bd700-fd5b-11e8-8a86-8761861d5a7b.gif)

![enabled](https://user-images.githubusercontent.com/771134/49828968-3b16c780-fd5b-11e8-8057-290a057283b1.gif)

**Comment by ghaschel** [comment]
How couldn't I notice that? Lol.

Apparently there is no easy way to inherit features from other languages.
I will take a look at this, maybe consuming a language server could fix it.

**Comment by ghaschel** [comment]
I changed the language id back to html for now until i have some spare time to figure it out about the language server thing. So it should be normal again by now.

I will keep this issue open though and keep it updated here.

**Comment by ghaschel** [comment]
Apparently, changing from `html` to `angular-html` not only broke support for CSS/SCSS Intelisense and autoclosing but also for Angular Language Services, and probably every extension that also uses the `html` id.

I tried implementing a language server. It made some of the HTML features work again, but i still didn't have both Angular Language Services and Intelisense working.

Changing it to `ng-template` though made Angular Language Services Work again, but Intelisense is still gone.

For now, the best thing to do, I guess, would be keeping it as `html`. Not sure how open would other extension's devs be to adding support for angular-html id and also, not sure how viable it would be to do so.

**Comment by ghaschel** [comment]
I won't be able to change the language id by now. Maybe in the future. Closing this as it was fixed already
