### ISSUE TITLE
Better color-coding

### ISSUE THREAD

**Issue by denspiro** [ghaschel/vscode-angular-html#2]
![image](https://user-images.githubusercontent.com/944858/47914345-ee141b80-dea7-11e8-9514-db4cc9f5a00c.png)

It would be nice to keep HTML tags as is because it creates a bit more stand-outs for those. When one-colored HTML tags harder to read.

**Comment by denspiro** [comment]
Since it's more personal preference, I would suggest to keep it as an option, so one who thinks different can switch this off.

**Comment by ghaschel** [comment]
Can you tell me what theme you're using? So that i can reproduce it here

You mean the expression inside *ngIf, right?

**Comment by denspiro** [comment]
Theme: https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme

"You mean the expression inside *ngIf, right?" -> Not exactly. I mean <></> around html tags. After "vscode-angular-html" is enabled, those became the same color (in my case red). Everything that relates to Angular expressions in "vscode-angular-html" is great. 

To create this screenshot, I disable "vscode-angular-html" and enable "[vscode-angular-syntax](https://marketplace.visualstudio.com/items?itemName=dunstontc.vscode-angular-syntax)" to show the end result. Sorry if it was confusing.

**Comment by denspiro** [comment]
You can check from previous issue  [here](https://github.com/ghaschel/vscode-angular-html/issues/1) It's how I see it after "vscode-angular-html" is enabled.

**Comment by ghaschel** [comment]
I agree with you. I fixed it in 0.0.20, thanks for pointing out.

Feel free to open another issue if needed, I am closing this one now
