### ISSUE TITLE
*matHeaderCellDef

### ISSUE THREAD

**Issue by yandiro** [ghaschel/vscode-angular-html#20]
Extension cant handle well codes like this

https://i.imgur.com/2tVAxML.png

Notice how the class="classaName" is not colored

**Comment by ghaschel** [comment]
Confirmed bug.
I'll investigate into it. Thank you for reporting it

**Comment by ghaschel** [comment]
Fixed in [1.1.3](https://github.com/ghaschel/vscode-angular-html/commit/a827f5931c3b76e85a6a05e028ace87f2678260b)
