### ISSUE TITLE
reserved words for component name

### ISSUE THREAD

**Issue by yandiro** [ghaschel/vscode-angular-html#22]
Great extension!

Just a little fix

![image](https://user-images.githubusercontent.com/27643901/63095229-22d9f680-bf41-11e9-9572-eb6dc9127df2.png)

Notice that the word buttons is in blue

**Comment by ghaschel** [comment]
Confirmed bug. Thank you for reporting it.

**Comment by ghaschel** [comment]
Fixed in (1.1.4)[https://github.com/ghaschel/vscode-angular-html/commit/01cdf0df3453e16c328aa1ef0dbd07608a1e6916]

Feel free to reopen this issue in case the fix doesn't work for you.
