### ISSUE TITLE
Support *ngIf wit `then` and `else`

### ISSUE THREAD

**Issue by Dassderdie** [ghaschel/vscode-angular-html#23]
I would expect the `then` and `else` to be in a different colour (e.g. like the `of` in `*ngFor`):
![image](https://user-images.githubusercontent.com/18506183/63546765-d7b87880-c52a-11e9-82ed-e79aef8587fe.png)

https://angular.io/api/common/NgIf

Btw.: Just found this extension today and love it ❤️

**Comment by ghaschel** [comment]
Thank you for the feedback! ❤️ 

This is definitely something that was missing.

**Comment by ghaschel** [comment]
Added in [1.2.0](https://github.com/ghaschel/vscode-angular-html/commit/40fe2ffea7510506ab17d08abf4e7fb3a54887fd)
