### ISSUE TITLE
Different color for component- and angular-structure-tags

### ISSUE THREAD

**Issue by Dassderdie** [ghaschel/vscode-angular-html#24]
I'm not quite sure about it, but I believe it could be quite helpful if all component-tags and angular-stuff like e.g. `ng-content`, `ng-template` and `ng-container` would have different colours than "normal" HTML-attributes.

**Comment by ghaschel** [comment]
This is actually a great idea. I'll look further into this. 

Thank you for the suggestion

**Comment by ghaschel** [comment]
Added angular structural color differentiation in [1.2.0](https://github.com/ghaschel/vscode-angular-html/commit/40fe2ffea7510506ab17d08abf4e7fb3a54887fd) 

Although I have not added to the prefixed `component-` ones due the fact it may make the highlighting too opinionated.

**Comment by Dassderdie** [comment]
I think you are right with your point about the component highlighting. Maybe this could be an own extension like `TODO: Highlight` or so...

I just noticed there is also `<router-outlet></router-outlet>` as an angular structural tag.

**Comment by ghaschel** [comment]
Sorry, completely forgot about `<router-outlet>`. Did it past midnight.

**Comment by ghaschel** [comment]
Fixed in [1.3.0](https://github.com/ghaschel/vscode-angular-html/commit/2b14c7ad37e7b6b26989ddbb9676132282e49967)
