### ISSUE TITLE
Different colour for pipes

### ISSUE THREAD

**Issue by Dassderdie** [ghaschel/vscode-angular-html#26]
I would expect pipes to have a different colour than "normal" variables (maybe the same as a function call):
![image](https://user-images.githubusercontent.com/18506183/63582925-441e9080-c59a-11e9-8d1f-9860d5af9256.png)

**Comment by ghaschel** [comment]
Added in [1.3.0](https://github.com/ghaschel/vscode-angular-html/commit/2b14c7ad37e7b6b26989ddbb9676132282e49967)
