### ISSUE TITLE
Non-prefix asterisk 

### ISSUE THREAD

**Issue by Dassderdie** [ghaschel/vscode-angular-html#27]
I think the single asterisk should have the same colour as the prefix one
![image](https://user-images.githubusercontent.com/18506183/63585409-53540d00-c59f-11e9-958b-9387ead58afe.png)

In case you are wondering the first line gets translated by angular to this:
![image](https://user-images.githubusercontent.com/18506183/63585879-661b1180-c5a0-11e9-8767-98bdd8a1ff15.png)
https://angular.io/guide/structural-directives#the-asterisk--prefix

**Comment by ghaschel** [comment]
Confirmed bug, thanks for reporting

**Comment by ghaschel** [comment]
Fixed in [1.3.0](https://github.com/ghaschel/vscode-angular-html/commit/2b14c7ad37e7b6b26989ddbb9676132282e49967)
