### ISSUE TITLE
Different color for structural directives

### ISSUE THREAD

**Issue by magnusbakken** [ghaschel/vscode-angular-html#28]
First off, thanks for the great work with this extension!

I'd like to have a more vivid color for structural directives, i.e. directives starting with `*`. Ideally I'd want to distinguish between `*ngIf`, `*ngFor` and maybe a few others, i.e. the directives that significantly alter the control flow of the document, but I'd be happy to just have a different color for all directives starting with asterisks.

Am I right in saying this isn't possible to do right now? I've been trying a few different things with VSCode's tokenColorCustomizations setting and poked around in the JSON files in this repo, but it seems like all I can do is override `constant.numeric.angular-directive`, which of course affects all directives. I guess what I want is something like `constant.numeric.angular-directive.structural`, so I can address *-directives specifically. I don't think there needs to be a separate color here by default; I just want a way to override it myself.

By the way, it would be great to have an overview of which custom scopes are available and what they mean.

**Comment by ghaschel** [comment]
Thank you for the feedback!

I think this is a great feature and it allow further customization via themes.

It's been on plans for some time now and I Intend to do it soon in a major update. 
I'd just like to add that even after a major update, I'd still need to address the directives using a contextually different scope name (eg. constant.numeric ~angullar-directive) due support to default themes, but still allowing to override a full scope.

Eg. All of the directives would have the default color, but using a custom theme, one could properly override their colors.

The current scopes are not fully documented yet, (that is to come too =P), but i have it [here](https://github.com/ghaschel/vscode-angular-html/blob/master/SCOPE-NAMES.md)

I'll do this as soon as I have some spare time left.

Feel free to add the directives you think should be separated here

**Comment by magnusbakken** [comment]
That sounds like a good plan.

Off the top of my head, I think some things that could be useful to distinguish from each other would be:
- Inputs (`[foo]="foo"`)
- Events (`(foo)="onFoo($event)"`
- Two-way bindings (`[(foo)]="foo"`, and probably the nonstandard but legal `([foo])` syntax as well)
- Structural directives (`*ngIf="foo"`)
- Variables (`#foo="foo"`)

The more the merrier I guess.

If I understand the scope system correctly, naming all of these `constant.numeric.angular.xyz` would give them the color of numeric constants by default, and you would have the option of overriding all of them with a rule targeting `constant.numeric.angular`, or each one separately using the whole name.

**Comment by ghaschel** [comment]
I believe this will be achievable in a future refactor. No ETA though

**Comment by ghaschel** [comment]
![image](https://user-images.githubusercontent.com/5878866/190808923-6a72ff01-b877-4630-8b71-a6a65060fd72.png)
 A quick preview of what is finally coming. This will be fixed in a near feature and the extra customizations will be optional

**Comment by ghaschel** [comment]
The refactor is complete. It should now match the default HTML.derivative scope or close to it, and you can now customize your extra-matched characters.

Please, refer to [THEMING](https://github.com/ghaschel/vscode-angular-html/blob/master/docs/THEMING.md) to check all the extra-matched characters.

The update was published a few minutes ago. Feel free to open another issue if you need to

😄
