### ISSUE TITLE
s tag isn't deprecated

### ISSUE THREAD

**Issue by Dassderdie** [ghaschel/vscode-angular-html#29]
The s-tag is displayed in a red color like this:
![image](https://user-images.githubusercontent.com/18506183/64777390-59b02600-d55a-11e9-8d1d-0501157541c5.png)

However according to  
[whatwg](https://html-differences.whatwg.org/#obsolete-elements) and [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/s) the s-tag isn't deprecated but has just changed in meaning ("The s element now represents contents that are no longer accurate or no longer relevant" https://html-differences.whatwg.org/#changed-elements)

**Comment by ghaschel** [comment]
Thank you for pointing it out =]

Fixed it in [1.3.1](https://github.com/ghaschel/vscode-angular-html/commit/28be9616e7ba966ec87384b3477f8268586a9881)
