### ISSUE TITLE
Single Quote causing issue

### ISSUE THREAD

**Issue by urielzen** [ghaschel/vscode-angular-html#3]
A single quote is making the characters after it look like a string

![image](https://user-images.githubusercontent.com/7947179/48164432-146ef800-e2a8-11e8-8b77-6f085d3a048f.png)

Also the "." or "?" characters are not showing purple like it says it the documentation they should be.
I have Dark+ theme (I think is the default one when I installed VSCode)
Thank u so much for this extension

**Comment by ghaschel** [comment]
I will take a look at this. thank you for reporting it.

About the operators, I think it is a limitation of the default theme. I currently am using [dark-plus-syntax](https://github.com/dunstontc/dark-plus-syntax). It's the same as the default one, but it have some improvements. Can you confirm me that changing theme solves the '?', '.', and '!' issue?

**Comment by ghaschel** [comment]
Issue with single quote fixed with [0.0.22](https://github.com/ghaschel/vscode-angular-html/commit/f7aa04216b6a2ac6b17273f534c782021240b6d9). I will wait for your answer about the '?', '!' and '.' before closing the issue.

**Comment by urielzen** [comment]
Thank u for fixing the bug. And you are correct, After installing the dark plus syntax theme, the operators show with purple color.

If you don't mind, can I ask about the decisions to use orange/red for the < /> characters in tags? I have a tendency to get distracted by the red color thinking that is some kind of lint error.

Thanks again.

**Comment by ghaschel** [comment]
Sure you can. Actually i didn't choose colors, just the scope names (in this case, i choose the same as the regex one because it is easier to see regex highlighting in themes).

But now that you have pointed it out, it makes sense. It does looks like some sort of linting error.

I think it's best to return it to the default color to keep it similar to other HTML highlithing aswell.

**Comment by ghaschel** [comment]
Color fixed in 0.0.23 =]
