### ISSUE TITLE
Customizable colors

### ISSUE THREAD

**Issue by adriansd27** [ghaschel/vscode-angular-html#30]
Hi! Amazing extension, really helpful. Although it would be really cool if you could choose colors for the elements.

Keep up the good work!

**Comment by ghaschel** [comment]
I'm afraid this isn't something I could implement quickly at the moment. But I will definitely consider doing it.
This wasn't the first time someone suggested this feature, and it may be actually a nice addition - and a good excuse for me to study a bit more the vscode environment.

Thanks for the feedback and thanks for taking the time to suggest it. =]

**Comment by ghaschel** [comment]
I would suggest you and any other person looking forward for this feature, to try to use vscode way to override themes scope colors.

Open command pallet > Inspect TM Scopes

Grab the top first scope

![image](https://user-images.githubusercontent.com/5878866/71733528-987b2c00-2e28-11ea-9704-3338b2a0c703.png)

`string.regexp` in this case

```

add the desired entries and then add this to your settings.json

"editor.tokenColorCustomizations": {
		"textMateRules": [
			{
				"scope": ["string.regexp"],
				"settings": {
					"foreground": "#cc66ff",
					"fontStyle": "bold"
				}
			}
		]		
	}
```

It simply works

![image](https://user-images.githubusercontent.com/5878866/71734133-f2302600-2e29-11ea-8045-869095221bf8.png)

Sadly, this implementation have its limitations. It may affect your main theme/other languages colors.

This way of doing it may become way more viable and stabilized after implementing #28

**Comment by ghaschel** [comment]
This will be fixed in a future refactor. No ETA though

**Comment by ghaschel** [comment]
![image](https://user-images.githubusercontent.com/5878866/190808642-02d62938-b7ab-4647-9373-7adcde149b3d.png)

Just a quick preview of what is finally coming

**Comment by ghaschel** [comment]
This was added on 2.0 and the update is now live. 

Feel free to open another issue if you need to.

😄
