### ISSUE TITLE
ReadMe Update Request

### ISSUE THREAD

**Issue by CagriAldemir** [ghaschel/vscode-angular-html#31]
Maybe you can add the following gif file to ReadMe file. I think this image will be more descriptive.

![before-after](https://user-images.githubusercontent.com/8038704/70740268-d7d2c300-1d29-11ea-9437-f9088ec876ff.gif)

**Comment by ghaschel** [comment]
Thank you for the idea. <3
I just did it now using Polacode.

Sorry for taking so long to answer. I was moving.
