### ISSUE TITLE
Warning Message for References to Private Component Members in Templates

### ISSUE THREAD

**Issue by bleistift-zwei** [ghaschel/vscode-angular-html#35]
I’m not sure if this is really an issue with the plugin… but closing this issue is easy if you disagree, so I’ll state my case.

The plugin warns when accessing private members in a component’s template. To be clear right away: I’ve come to the conclusion that this is **good**. However, neither does the default Angular compiler reject access to private members, nor do the Angular docs discourage it. So at first, I intended to report this feature as a bug.

In order to avoid future confusion, I suggest elaborating on why this warning is generated. I’m personally a fan of ESLint’s documentation pages in which each rule has its justification, but that might be overkill for this project. So drawing information from [this answer on StackOverflow](https://stackoverflow.com/a/39000046/6144146) I suggest amending the error description:

>Identifier '‹identifier›' refers to a private member of the component. This may cause problems with ahead-of-time compilation, see https://angular.io/guide/aot-compiler#public-symbols

**Comment by ghaschel** [comment]
I am closing as this doesn't refer to my plugin, and yes to [angular-language-service](https://github.com/angular/vscode-ng-language-service)
