### ISSUE TITLE
Allow Disabling Warnings

### ISSUE THREAD

**Issue by bleistift-zwei** [ghaschel/vscode-angular-html#36]
It would be nice if we were able to ignore certain warnings, e.g. the one I mentioned in [my other issue](https://github.com/ghaschel/vscode-angular-html/issues/35).

This would give you the chance to look into how VSCode manages user configurations =)

The use case for the real world would be taking over a large project in which all members were declared private. This makes the file explorer look like a christmas tree. Since the color for the warned files is similar to the one that is used for displaying files that have changed relative to the Git HEAD, this can get annoying quickly.

**Comment by ghaschel** [comment]
Hi, sorry for taking so long to answer. I have been very busy lately. I'm afraid the issue you are having refers to [angular-language-service](https://github.com/angular/vscode-ng-language-service) as my extension doesn't deal with the angular language errors. It only adds Syntax Highlighting...

**Comment by bleistift-zwei** [comment]
I’m sorry to have bothered you. Thanks for pointing me in the right direction.

And BTW 2 days response time for a private project isn’t half bad.
