### ISSUE TITLE
Plugin broken on newer versions of VSCode?

### ISSUE THREAD

**Issue by hrmcdonald** [ghaschel/vscode-angular-html#39]
I really loved this plugin, but on newer versions of VSCode it appears to no longer work. This started happening probably around the July or August 2020 update. If you happen to still be maintaining this, it would be awesome if you could check this out.

**Comment by ghaschel** [comment]
That's weird to be honest, I am using it daily and have never had a issue. Can you please share with me what plugins are you using alongside this one, please?

**Comment by hrmcdonald** [comment]
Hmm, thanks for the response. I'll try this plugin alone to confirm and then try to isolate where a conflict could exist.

**Comment by hrmcdonald** [comment]
I was able to check this out and after cleaning up my extensions a bit I can confirm this one is working again!

**Comment by ghaschel** [comment]
I'm glad I could help.
