### ISSUE TITLE
Class names in white instead of orange

### ISSUE THREAD

**Issue by urielzen** [ghaschel/vscode-angular-html#4]
Class names for <label> and <span> elements are shown in white instead of orange.

![image](https://user-images.githubusercontent.com/7947179/48177251-52d0db00-e2d9-11e8-98a4-2bace293f0d3.png)

**Comment by ghaschel** [comment]
I am looking into this. Thanks for pointing out

**Comment by ghaschel** [comment]
fixed in [0.0.23](https://github.com/ghaschel/vscode-angular-html/commit/ac9aa258ad8a05eac80abd23636222e7bfa0d29f)
