### ISSUE TITLE
Incorrect color for asterisk directly before end of the html-tag

### ISSUE THREAD

**Issue by Dassderdie** [ghaschel/vscode-angular-html#40]
```html
<div * class="container"></div>

<div * ></div>

<!-- This asterisk should have the same color as above -->
<div *></div>
```

![image](https://user-images.githubusercontent.com/18506183/99908233-c045dd80-2ce1-11eb-95e3-7fbc91f5f3da.png)

An easy workaround is to insert a space before the end of the tag, but e.g. prettier formats it without the space.

[Reference about the asterisk](https://angular.io/guide/structural-directives#the-asterisk--prefix)

**Comment by urielzen** [comment]
what does an asterisk do on it's own as a parameter?

**Comment by Dassderdie** [comment]
@urielzen 
As you can see [here](https://angular.io/guide/structural-directives#the-asterisk--prefix) the asterisk is just a syntactic sugar for `ng-template`. This means the following two code snippets are equivalent:

```html
<div *></div>
```
and
```html
<ng-template><div></div></ng-template>
```

I use this in the following way:

```html
<app-animated-if>
    <app-settings *></app-settings>
</app-animated-if>
```
The `AnimatedIfComponent` requires a template to be inserted to make sure the stuff that should be conditionally shown is not loaded before (= works like *ngIf). And it is done over the Contents and not another attribute because so its easier to read in the code.

**Comment by urielzen** [comment]
@Dassderdie thanks for the info, I didn't know this. I knew ng-template was used for structural directives but I never realized you could actually use the * by itself without ngIf... etc.

Btw, I just tested it in my vscode and the asterisk shows red as expected.

**Comment by Dassderdie** [comment]
Strange, I can reproduce it even if only `vscode-angular-html` and `dark-plus-syntax` are enabled... - I try to check it tomorrow on a second device...

**Comment by ghaschel** [comment]
I'm sorry for the late response. I will look further into this. But as for now I can also confirm it does not reproduce on my machine.

![image](https://user-images.githubusercontent.com/5878866/99965213-4c541580-2d73-11eb-8bab-89461931fae1.png)

What OS and VSCode version are you running it on?

**Comment by Dassderdie** [comment]
It reproduces for me on my laptop too. Both machines run Windows 10 and the most recent vscode.

*vscode-angular-html* v1.7.0
*dark-plus-syntax* v0.0.167

Is there anything else I could log?

**Comment by Dassderdie** [comment]
I found the problem: I have font ligatures enabled, therefore `*>` is one symbol which has only one color.

Sorry for the inconvenience...

**Comment by ghaschel** [comment]
Oh, no problems. Feel free to open another one if necessary.
