### ISSUE TITLE
Valid component names can break highlighting

### ISSUE THREAD

**Issue by AlexsaniKY** [ghaschel/vscode-angular-html#48]
Syntax highlighting is broken when certain strings are used in the name. Using a custom angular component starting with 'style' causes all template highlighting to stop from that point onwards in the file.

Example: `<style-preview-component></style-preview-component>` would highlight the substrings 'style', '-preview-componen', 't' separately, and then break template highlighting for the rest of the template document.
![image](https://user-images.githubusercontent.com/8084279/166494277-15f4c339-5384-407f-892d-fdb3c55424cf.png)

**Comment by AlexsaniKY** [comment]
It does not resume highlighting until it sees a 'style' closing tag, despite that being malformed html (closing a tag that was never opened)

**Comment by ghaschel** [comment]
I'm on it!

**Comment by ghaschel** [comment]
The update is live now https://marketplace.visualstudio.com/items?itemName=ghaschel.vscode-angular-html

**Comment by AlexsaniKY** [comment]
Fantastic. I like this extension for my workflow, nice turnaround.
