### ISSUE TITLE
Unexpected colors

### ISSUE THREAD

**Issue by EinfachHans** [ghaschel/vscode-angular-html#49]
See attached image:

![Bildschirmfoto 2022-06-02 um 12 08 25](https://user-images.githubusercontent.com/20899975/171607435-d721000a-fde0-4178-bd3a-8bc08bcf91da.png)

I would expect the `class`, `vertical`, and stuff to not be in the same color here. Also i would expect my variables like `isEnvironmentFabVisible`, `environmentLabel` and more to be not white (i know them in a purple from InteliJ). 

Is this the expected look a like?

**Comment by theophile-wallez** [comment]
I have the same issue, could this be fixed?

**Comment by ghaschel** [comment]
Sorry for the long delay.

I'll try to reproduce. Can you list you installed extensions and selected theme please?

**Comment by theophile-wallez** [comment]
I've disabled all extensions except yours and One Dark Pro and still got this result: 
<img width="551" alt="image" src="https://user-images.githubusercontent.com/66305625/177662299-f0f17180-796f-41a6-ae19-65afd72cd9db.png">

VSCode version: 1.68.1,
Angular CLI: 13.2.6
Node: 14.18.0

Btw, I have a correct syntax highlighting when using the vscode-angular-syntax extension on which this project is based on: 
<img width="755" alt="image" src="https://user-images.githubusercontent.com/66305625/177663406-1620e21a-67e6-4939-ad74-de2493026cb2.png">

**Comment by ghaschel** [comment]
Sorry for the late answer. It has been a really busy period for me. But I'll take a look at this now

**Comment by ghaschel** [comment]
Hey. I was able to look into this issue.

The thing is, I developed this highlighting plugin to be very colorful and ADHD friendly as I was struggling at the time.
But the thing is, I developed it without much planning ahead or studying it properly.

You are actually getting the "correct" highlighting as I was using wrong scope names, based only on the color it showed at the time.

I am planning now in a complete refactor of this plugin using proper scope definition and semantic scopes, allowing then, users to use different themes and also, make color tweaks via settings file... Sorry about this. 

I will release it, but I can't put a ETA to it as I started it basically yesterday.

**Comment by ghaschel** [comment]
The refactor is complete. It should now match the default HTML.derivative scope or close to it, and you can now customize your extra-matched characters.

The update was published a few minutes ago. Feel free to open another issue if you need to

😄
