### ISSUE TITLE
Self closing tags changing color

### ISSUE THREAD

**Issue by urielzen** [ghaschel/vscode-angular-html#5]
Forward slash for self closing tags is shown blue instead of grey.

![image](https://user-images.githubusercontent.com/7947179/48208954-a115c680-e339-11e8-8723-fcf32e009b4d.png)

Thanks a lot!

**Comment by ghaschel** [comment]
Fixed in [0.0.24](https://github.com/ghaschel/vscode-angular-html/commit/c1240c421bf12f44ed00bf0ecca534ddcd58bb61)

Thank you! =]
