### ISSUE TITLE
Color schemes for inline template

### ISSUE THREAD

**Issue by BachiMjavanadze** [ghaschel/vscode-angular-html#50]
Color schemes for inline templates doesn't works properly:

![image](https://user-images.githubusercontent.com/38082501/182891944-137adcaf-d830-4074-8f2f-80e0409330c9.png)

my settings.json:

`
"emmet.includeLanguages": {
        "javascript": "html",
        "typescript": "html"
    }
`

please fix it.

**Comment by ghaschel** [comment]
This plugin doesn't support inline templates, as it is exclusively for template as HTML files. I am currently developing the inline template version. Please refer to this [plugin](https://github.com/ghaschel/vscode-angular-ts).

You should expect it to be released in the next week as a beta version.

**Comment by ghaschel** [comment]
A bit earlier than I planned. But yeah, here it is: [Inline Template Support](https://marketplace.visualstudio.com/items?itemName=ghaschel.vscode-angular-inline)

**Comment by BachiMjavanadze** [comment]
@ghaschel May I ask you to look at this extension? It's very good extention for all languages that are using Terminal:

[https://marketplace.visualstudio.com/items?itemName=easterapps.script-runner](https://marketplace.visualstudio.com/items?itemName=easterapps.script-runner)

The author doesn't responds. Maybe you will make fork of it, rename to `Terminal snippets` and implement my two Issues (Feature request). Chek my settings for Angular (from empty VSCode you can generate project without any questions):

![image](https://user-images.githubusercontent.com/38082501/183239633-8e1cd9ae-f8f7-4b34-84ac-ac3021162992.png)

into settings.json (I'm on Windows, so on Mac or Linux my commands will not work, you need to correct them a bit. Do not forget to define your default working folder, mine is: 'D:\Documents\Development'):

`/* __________ Script Runner __________ */
"script-runner.statusBar": true,
"script-runner.definitions": {
    "variables": {
        "$path": "D:\\Documents\\Development"
    },
    "commands": [
        {
            "identifier": "Angular 1",
            "description": "Angular - create project + ESlint + CSS",
            "command": "ng new $var1 --style=css --routing=false; cd $var1; ng add @angular-eslint/schematics --skip-confirmation=true; ng lint; code -r .",
            "working_directory": "$path",
            "form": [
                {
                    "variable": "$var1",
                    "question": "Project name"
                }
            ]
        },
        {
            "identifier": "Angular 2",
            "description": "Angular - create project + ESlint + CSS + Routing",
            "command": "ng new $var1 --style=css --routing=true; cd $var1; ng add @angular-eslint/schematics --skip-confirmation=true; ng lint; code -r .",
            "working_directory": "$path",
            "form": [
                {
                    "variable": "$var1",
                    "question": "Project name"
                }
            ]
        },
        {
            "identifier": "Angular 3",
            "description": "Angular - create project + ESlint + SCSS",
            "command": "ng new $var1 --style=scss --routing=false; cd $var1; ng add @angular-eslint/schematics --skip-confirmation=true; ng lint; code -r .",
            "working_directory": "$path",
            "form": [
                {
                    "variable": "$var1",
                    "question": "Project name"
                }
            ]
        },
        {
            "identifier": "Angular 4",
            "description": "Angular - create project + ESlint + SCSS  + Routing",
            "command": "ng new $var1 --style=scss --routing=true; cd $var1; ng add @angular-eslint/schematics --skip-confirmation=true; ng lint; code -r .",
            "working_directory": "$path",
            "form": [
                {
                    "variable": "$var1",
                    "question": "Project name"
                }
            ]
        },
    ],
},`
