### ISSUE TITLE
Tags not displaying properly

### ISSUE THREAD

**Issue by vaindil** [ghaschel/vscode-angular-html#6]
Most of my tags aren't displaying colors properly. I'm using the recommended [dark-plus-syntax](https://marketplace.visualstudio.com/items?itemName=dunstontc.dark-plus-syntax) theme.

You can see that the very top line has the issue, as well as each of the tags at the very bottom.

![example screenshot](https://user-images.githubusercontent.com/771134/48350626-d41bcb00-e655-11e8-9326-dcb08fb582ce.png)

For testing, this is a code snippet:

```html
<div class="row no-gutters" *ngIf="selectedCustomer && selectedCustomer.id > 0">
  <div class="col">
    <kendo-grid #grid="kendoGrid"
        *ngIf="!isExternalCheckIn"
        [data]="gridView"
        (cellClose)="onCellClose()">
      <kendo-grid-column field="partTypeId" hidden="true"></kendo-grid-column>
      <kendo-grid-column field="partName" title="Part" [editable]="false"></kendo-grid-column>
      <kendo-grid-column field="partNumber" title="Part #" [editable]="false"></kendo-grid-column>
    </kendo-grid>
  </div>
</div>
```

**Comment by ghaschel** [comment]
Thanks for reporting it. Just figured it out here. =]

**Comment by ghaschel** [comment]
[0.0.26](https://github.com/ghaschel/vscode-angular-html/commit/2518221631aab431517f24417b1c680ab9b6864f) fixes this

**Comment by vaindil** [comment]
Just updated, looks great now. Thanks for the quick fix!
