### ISSUE TITLE
Dot separated event listeners not colored properly

### ISSUE THREAD

**Issue by raamwerk** [ghaschel/vscode-angular-html#68]
![image](https://user-images.githubusercontent.com/36499578/197491546-d70e32b7-12fc-4bb8-bc92-b244dca0cb32.png)

**Describe the bug**
 - When using a period in an event binding (eg `(keydown.enter)`), colors are not applied. I believe they used to before the recent big update.

**Expected behavior**
 - At least same colors when using single level event listeners, but possibly multiple level colors, as is the case with other types of bindings.

**Comment by ghaschel** [comment]
On it.

**Comment by ghaschel** [comment]
This was fixed in v2.2.1.

Feel free to reopen or open a new issue if there's something wrong
