### ISSUE TITLE
Syntax highlighting not working on versions ^2.0.0 ( Linux )

### ISSUE THREAD

**Issue by zeljkoantich** [ghaschel/vscode-angular-html#70]
**Describe the bug**
 - After updating from VSCode v1.71.2 to v1.72.2 and plugin auto update to v2.0.0, the syntax highlighting stopped working.
 - Syntax highlighting doesn't work on any of this versions: v2.0.0, v2.0.2, v2.1.0, v2.2.1. 

**List of installed/enabled extensions**
```
adamwalzer.scss-lint
AlanWalk.markdown-toc
Angular.ng-template
bierner.markdown-mermaid
bmalehorn.vscode-fish
CoenraadS.bracket-pair-colorizer
cyrilletuzi.angular-schematics
darkriszty.markdown-table-prettify
dbaeumer.vscode-eslint
donjayamanne.githistory
eamodio.gitlens
gencer.html-slim-scss-css-class-completion
ghaschel.vscode-angular-html
janisdd.vscode-edit-csv
jock.svg
johnpapa.vscode-peacock
jpoissonnier.vscode-styled-components
mechatroner.rainbow-csv
mhutchie.git-graph
ms-vscode.sublime-keybindings
msjsdiag.debugger-for-chrome
PKief.material-icon-theme
redhat.vscode-xml
redhat.vscode-yaml
sibiraj-s.vscode-scss-formatter
SimonSiefke.svg-preview
skyapps.fish-vscode
streetsidesoftware.code-spell-checker
wayou.vscode-todo-highlight
wwm.better-align
yzane.markdown-pdf
```
**OS (please provide the following information):**
 - OS and Version: Linux Mint 20 Cinnamon ~ Ubuntu Focal 20.04 (LTS)
 - VSCode version: 1.72.2 x64

**Expected behavior**
 - Plugin should do syntax highlighting as before.

**Additional context**
 - Appearance on v2.0.0. **Syntax highlighting is not working**:
 ![ghaschel vscode-angular-html-v2 0 0-not-working](https://user-images.githubusercontent.com/34521192/197939324-f08f11c2-ab0f-441d-95ae-3308d0852912.png)

 - Appearance on v1.8.4. **Syntax highlighting works**:
 ![ghaschel vscode-angular-html-v1 8 4-working](https://user-images.githubusercontent.com/34521192/197939566-1764599b-d6f8-4805-acde-32c03632f20f.png)

**Comment by ghaschel** [comment]
Please. run the "vscode-angular-html: Set legacy color customizations" command.

The extra-matched elements are no longer the default highlighting, but now, the extra-matched characters works in different themes. Please, check the readme for any refferences. I will update the readme, and add a F.A.Q. covering this, and update the github issues to add a theme support change/request.

Let me know if running the command works for you. Thank you :)

**Comment by zeljkoantich** [comment]
Running `vscode-angular-html: Set legacy color customizations` works.

Thanks @ghaschel.

**Comment by ghaschel** [comment]
I'm glad. Feel free to create another issue if you find anything wrong. 

Thank you :)
