### ISSUE TITLE
Template syntax highlighting no longer works since v2.0.0

### ISSUE THREAD

**Issue by benjamin-achouche** [ghaschel/vscode-angular-html#72]
Hi,

I noticed that this morning, syntax highlighting in my project was gone. I can only assume it's because of the last update that was applied on 07/11/22.

![image](https://user-images.githubusercontent.com/80125093/200512093-fbe1b71a-6171-4a89-8839-536728046df8.png)

Can you help ?

Thanks !

EDIT: Apparently I was wrong, because when I rollback to previous versions up until 2.0.0, it still doesn't work. 1.8.4 does though. Maybe I just didn't notice up until now somehow ?

Anyway, it doesn't work for me from v2.0.0 on.

**Comment by ghaschel** [comment]
Please. run the "vscode-angular-html: Set legacy color customizations" command.

The extra-matched elements are no longer the default highlighting, but now, not only, the extra-matched characters works properly in different themes, but you can also customize your extra-matched characters via extension settings. Please, check the readme and the F.A.Q. for any references.

Let me know if running the command works for you. Thank you :)

**Comment by ghost** [comment]
> Please. run the "vscode-angular-html: Set legacy color customizations" command. 
> Let me know if running the command works for you. Thank you :)

I had the same problem and it was showing me this
![Screenshot 2022-11-10 at 10 39 25](https://user-images.githubusercontent.com/89575566/201069527-f694fdd8-056a-4195-8c91-dfa63103082b.png)

 every time I changed a setting and not applying changes, but your command applies the changes.

While it works, I guess you should review this issue.

And thank s for your work. This really helps making code easier to read ;)

**Comment by ghaschel** [comment]
That's a bug, just confirmed myself.

Thank you for reporting it. I'll fix it soon.

**Comment by ghaschel** [comment]
This was fixed in v2.2.2.

**Comment by ghost** [comment]
Just tested it, works great. Thank you!
