### ISSUE TITLE
Extension has no effect anymore

### ISSUE THREAD

**Issue by JonathanSzekely** [ghaschel/vscode-angular-html#78]
**Have you read the F.A.Q.?**

I can't, the link is broken
![UvuOcnHEWl](https://user-images.githubusercontent.com/47614934/208290191-f4aac8a9-70f9-4e1a-b1a2-7f9279083571.png)

**Describe the bug**

The extension doesn't have any effect whatsoever

**List of installed/enabled extensions**
Provide a list of installed/enabled extensions. Also, try to pinpoint which extension might be conflicting with the current one if that's the case.

Angular.ng-template
dbaeumer.vscode-eslint      
ghaschel.vscode-angular-html

**OS (please provide the following information):**

Windows 10 Pro, v 10.0.19044 build 19044
VSCode v 1.74.1

**Expected behavior**

I need the extension to apply angular syntax highlighting through colors like it did before

**Additional context**

I'm not sure when and how it stopped working, I noticed it about a week ago.

I tried reinstalling the extension, ran the  "vscode-angular-html: Set legacy color customizations command", even reinstalled vscode fully and cleanly, and still nothing

Also checked out the other issues about this and tried 1.8.4 version and that one works right out of the box

**Comment by jackiems82** [comment]
The same happens for me as well. Fresh install of VSCode with some Angular related plugins. I also ran the  "vscode-angular-html: Set legacy color customizations command" with no effect.

**Comment by ghaschel** [comment]
On it.

Sorry for the long time to answer, had a crazy week.

This is probably related to webpack and I'll try to reproduce it and come up with a bugfix fast. Weird thing is that this is actually working in mine and my coworker workspace.

Two things I need from you guys:
- What is the current output for the Legacy colors command? Is there any error message popping up?
- When you run the legacy colors command, does a settings.json file open up quickly and closes back again?
- And also, can you please print the output of the "Inspect Editor Tokens and Scopes" command for vscode in a HTML file? ( just to make sure this isn't something to do with grammar)

It should look something like this:
![image](https://user-images.githubusercontent.com/5878866/209178436-c7a6910b-0753-491b-b88d-c7186b948292.png)


Thanks in advance

**Comment by ghaschel** [comment]
Also: Can you please tell me if this config is enabled in the settings page?

![image](https://user-images.githubusercontent.com/5878866/209170506-87f9fa36-5b02-44fc-9394-0fb847806f19.png)

**Comment by ghaschel** [comment]
I'm really in the dark with this one but I have some things that may shed a light on this issue and I need your help with:

I tried:
- Different language packs
- Disabling the color customizations via settings and running the command again.
- Disabling all of my extensions except for the ones you mentioned

So far nothing causes the extension not to work.

I am running VSCode 1.74.2 (user setup)

- If the issue you reported is happening in the latest version (2.3.4), could you please install different versions and report back to me in which version does it start to work back to you?
- Are you using any VSCode display language pack?
- Does this folder looks similar as this to you?
![image](https://user-images.githubusercontent.com/5878866/209176632-2c52804f-ca44-4e44-b2a1-7fe6b2ea6e54.png)

**Comment by jackiems82** [comment]
Sorry for the delay. I switched to using Webstorm in the meantime. However, I hope to provide some answers that help.

- What is the current output for the Legacy colors command? Is there any error message popping up?
  -> Not quite sure what exactly you mean. There is no output inside the Output pane.
- When you run the legacy colors command, does a settings.json file open up quickly and closes back again?
  -> Yes it does. Though I believe before trying different versions simply nothing was happening. 
<img width="218" alt="image" src="https://user-images.githubusercontent.com/10219138/210538240-924b508d-c079-4103-b285-e93a3ee6014e.png">

- The mentioned config option is enabled.
- Version 2.2.2 works, 2.3.0 does not.
- No language pack, basically fresh install with some plugins:
  <img width="167" alt="image" src="https://user-images.githubusercontent.com/10219138/210537810-0a8f3f98-9b51-4afa-9bb6-7eb99e8465e6.png">
- The folders are the same

**Comment by ghaschel** [comment]
This took me a while. But it was fixed. It is still not available due an issue with the VSCode publishing life-cycle. It seems the unavailability of one of the badge hosting websites may be causing the extension not to be approved. 

As soon as this is resolved, I will publish the fix

**Comment by ghaschel** [comment]
Publishing resolved. It should be fixed in the last version. Can someone confirm it for me, please?

**Comment by JonathanSzekely** [comment]
Thank you for taking the time! I will check it and let you know soon

**Comment by ghaschel** [comment]
I got confirmation this is working now. Thanks for your help, guys. And thanks for taking the time to report this.
