### ISSUE TITLE
Support Darcula Theme

### ISSUE THREAD

**Issue by ThomasGaboriau** [ghaschel/vscode-angular-html#79]
**Is your request a change or a new theme?**

- [ ] Change
- [X] Request

**What is the theme name and link?**
[Darcula Theme](https://marketplace.visualstudio.com/items?itemName=rokoroku.vscode-theme-darcula)

**Describe the suggested improvement/change**
Very similar to [Darcula Theme - WebStorm Edition](https://marketplace.visualstudio.com/items?itemName=rexebin.dracula).
Currently, I switch to the Webstorm Edition, apply the legacy colors, then switch back to Darcula, and it looks really fine.

**Comment by ghaschel** [comment]
On it. Sorry for the late response

**Comment by ghaschel** [comment]
Implemented on 2.5.0. Please let me know if it works for you

**Comment by ThomasGaboriau** [comment]
Works fantastic thank you so much !
