### ISSUE TITLE
Do you plan to support pug?

### ISSUE THREAD

**Issue by CatsMiaow** [ghaschel/vscode-angular-html#8]
I am using a [pug](https://pugjs.org) as a template.
Do you plan to support pug?

<img width="978" alt="2018-11-14 7 05 47" src="https://user-images.githubusercontent.com/1300172/48475515-57991000-e840-11e8-8dcb-235c2ee93931.png">

**Comment by EricChoiKR** [comment]
I want to this feature too.

**Comment by ghaschel** [comment]
That would be nice, i have never thought of doing it.
Creating a new repository to start developing it.

**Comment by ghaschel** [comment]
As it is another syntax, i will need to release as another plugin. You can follow the progress [here](https://github.com/ghaschel/vscode-angular-pug)

**Comment by ghaschel** [comment]
First version is available =]

https://marketplace.visualstudio.com/items?itemName=ghaschel.vscode-angular-pug

Feel free to open an issue if there is anything wrong.
