### ISSUE TITLE
Legacy color customizations not working on VSCode Dark Modern theme

### ISSUE THREAD

**Issue by mangonator** [ghaschel/vscode-angular-html#87]
I noticed this bug when using the new Dark Modern - theme in my VS Code:

When running the command 
`> vscode-angular-html: Set legacy color customizations`
the syntax highlighting  colors are not set, extension is running on default colors

If i change the theme in vscode to Dark+ and run the legacy color command, the syntax highlighting colors are set correctly.

If i then switch back to Dark Modern - theme, syntax highlighting colors remain correct. 

**Have you read the F.A.Q.?**

- [ ] No
- [x] Yes, but my issue has nothing to do with anything in there, or it does but something is broken.

**Describe the bug**

It appears there is a bug somewhere when using `vscode-angular-html: Set legacy color customizations` command while Dark Modern theme is enabled, or the theme is not supported currently

**List of installed/enabled extensions**
alefragnani.Bookmarks
alexiv.vscode-angular2-files
Angular.ng-template
bradlc.vscode-tailwindcss
christian-kohler.npm-intellisense
dbaeumer.vscode-eslint
DotJoshJohnson.xml
eamodio.gitlens
EditorConfig.EditorConfig
ghaschel.vscode-angular-html
GitHub.copilot
jeremyrajan.webpack
johnstoncode.svn-scm
ms-vscode-remote.remote-wsl
ms-vsliveshare.vsliveshare
shardulm94.trailing-spaces
thekalinga.bootstrap4-vscode
VisualStudioExptTeam.intellicode-api-usage-examples
VisualStudioExptTeam.vscodeintellicode
Zignd.html-css-class-completion

**OS (please provide the following information):**

Windows 11
vscode version 1.80.1

**Expected behavior**

Legacy colors are set correctly when running the command 
`> vscode-angular-html: Set legacy color customizations`

**Comment by ghaschel** [comment]
I'm sorry about the huge delay

This theme is now supported in [v2.7.1](https://marketplace.visualstudio.com/items?itemName=ghaschel.vscode-angular-html)
