### ISSUE TITLE
highlighting interpolation syntax in attribute values

### ISSUE THREAD

**Issue by vLutsevich** [ghaschel/vscode-angular-html#9]
It seems that double curly braces in attribute values must be red color and expression inside of them must be blue as between HTML element tags 
![2018-11-19_12-07-03](https://user-images.githubusercontent.com/8142982/48696710-c0430c80-ebf3-11e8-8ba5-c5a7a1db17a0.png)
because it's must to showing that it's some data binding as red color for braces in data or event binding syntax.
![image](https://user-images.githubusercontent.com/8142982/48696979-7dcdff80-ebf4-11e8-8b46-ec1db74c03ac.png)

**Comment by ghaschel** [comment]
[0.0.31](https://github.com/ghaschel/vscode-angular-html/commit/63f3763f5d15ad1a584317653e8bbef8e2e8c137) fixes this
