### ISSUE TITLE
Support for "Visual Studio 2019 Dark plus syntax"

### ISSUE THREAD

**Issue by urielzen** [ghaschel/vscode-angular-html#93]
**Is your request a change or a new theme?**

- [ ] Change
- [x] Request

**What is the theme name and link?**

[Visual Studio 2019 Dark plus syntax](https://marketplace.visualstudio.com/items?itemName=skyletoft.theme-custom-colour)

**Comment by ghaschel** [comment]
On it.

**Comment by ghaschel** [comment]
Done. It is available on v2.9.0.

Should be live at any minute
