### ISSUE TITLE
Breaking interaction with "HTML CSS Support" by ecmel

### ISSUE THREAD

**Issue by ghaschel** [ghaschel/vscode-angular-html#94]
![image](https://github.com/ghaschel/vscode-angular-html/assets/5878866/e76934e1-a304-4176-ba87-118d8e1013e5)
![image](https://github.com/ghaschel/vscode-angular-html/assets/5878866/38ab42a3-7bc9-4362-b2ef-63299974f282)

**Comment by ghaschel** [comment]
I tried installing this extension and it didn't work out of the box. I had to add these settings manually in order for it to work:

```
{
    ...
    "css.enabledLanguages": ["html"],
    "css.styleSheets": ["src/**/*.css"],
    ...
}
```

After adding this settings it worked as it should:

![image](https://github.com/ghaschel/vscode-angular-html/assets/5878866/e062fe85-10e8-4567-83e3-b70229f89943)
![image](https://github.com/ghaschel/vscode-angular-html/assets/5878866/36a69347-19cf-4b62-8e3e-b7607d42235d)

If that doesn't work, please, provide me also your `settings.json`, VSCode version and OS so that I can replicate your settings.

If it works, let me know so I can close this

**Comment by NeuSandeZ** [comment]
![2134](https://github.com/ghaschel/vscode-angular-html/assets/44132675/a8f1cdb9-3856-414b-9cfa-8c445e9f2922)
[settings.json](https://github.com/ghaschel/vscode-angular-html/files/14229341/settings.json)
[settings.json](https://github.com/ghaschel/vscode-angular-html/files/14229343/settings.json)

Version: 1.86.1 (user setup)
Commit: 31c37ee8f63491495ac49e43b8544550fbae4533
Date: 2024-02-07T09:08:20.941Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by ghaschel** [comment]
@NeuSandeZ I fixed this. It should be available as starting from `v2.10.2`.

Please, let me know if somehow it is still not working for you.

**Comment by NeuSandeZ** [comment]
@ghaschel Works perfectly fine right now! Thank you i appreciate it!!

**Comment by ghaschel** [comment]
I'm glad to hear that! Thanks for letting me know.
